# Generated by Django 4.0.4 on 2022-05-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='portfolio/images')),
                ('Url', models.URLField(blank=True)),
            ],
        ),
    ]
