# Generated by Django 4.0.4 on 2022-05-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Categoria',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
